name: Intro_to_Pytorch
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=10.2
  - pytorch
  - torchvision
  - ipykernel
  - scikit-learn
  - matplotlib
  - tensorboard
  - libarchive
  - pandas
  - notebook
  - onnx